### ISSUE TITLE
Figure caption not working

### ISSUE THREAD

**Issue by AidanNichol** [vokimon/markdown-customblocks#3]
I'm trying to use a figure block within Mkdocs. using your test data
```
 ::: figure "https://via.placeholder.com/300.png"
      This figure is awsome
```
It is being rendered as
```
<figure>
   <a href="https://via.placeholder.com/300.png" data-wm-adjusted="done">
      <img src="https://via.placeholder.com/300.png">
   </a>
   <figcaption></figcaption>
</figure>
<p>This figure is awsome</p>
```
I don't seem to be able to get the content of the block to be used for the caption

**Comment by AidanNichol** [comment]
forget it. I've solved it.

I'm using VSCode for my editor and when it indents it was only doing 3 spaces and not 4.

**Comment by vokimon** [comment]
Ok, thanks for reporting anyway.
