### ISSUE TITLE
Block matching regex issue

### ISSUE THREAD

**Issue by eddiezab** [vokimon/markdown-customblocks#6]
Thanks for the tool. I encountered an issue that was a little unclear at first:

Currently blocks do not match if there is a spurious space after the marker.

For example: 

`::: note`

Will render however, 

`::: note `  will not match the regex and never be processed.

**Comment by vokimon** [comment]
Adding an space after note works for me. Could you please attach a failing md file, the console output and the generated output? Also would be nice if you specify the version of the customblocks packages your are using.

Thanks.

**Comment by vokimon** [comment]
Thanks, that helped. Now its fixed and will be in the next version soon.
