### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by aleray** [vokimon/markdown-customblocks#9]
Hello,

using Python 3.11, Pip 23.3.2 and setuptools 69.0.3 I get this error:

```
INFO    -  DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
```

The error is raised by this statement:

https://github.com/vokimon/markdown-customblocks/blob/master/customblocks/customblocks.py#L16

Thanks!

**Comment by vokimon** [comment]
Thanks for the report. This should be fixed since 1.5.0.
